org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

# Mod Properties
mod_id=gunmod
mod_name=Gun Mod
mod_version=1.0.0
mod_author=Novo Codigo

# Forge/Minecraft Properties
minecraft_version=1.21.11
forge_version=61.2.0
mapping_channel=official
mapping_version=1.21.1