# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[61,)"
license="All Rights Reserved"
#issueTrackerURL="https://github.com/MyOrganization/MyMod/"
#clientSideOnly=true , default=false

[[mods]]
modId="gunmod"
version="1.0.0"
displayName="Gun Mod"
#updateJSONURL="https://example.com/updates.json"
#displayURL="https://example.com/"
#logoFile="examplemod.png"
credits="Krauss"
authors="Novo Codigo"
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''A simple gun mod.'''

[[dependencies.gunmod]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gunmod]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"
